import { Database } from './database' // This should be the file generated by Supabase CLI

export type Business = Database['public']['Tables']['businesses']['Row']
export type ShortUrl = Database['public']['Tables']['short_urls']['Row']

export interface ShortUrlQueryResult {
    id: ShortUrl['id']
    businesses: Business | null
}